version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-bluediff
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blue_diff
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: America/Sao_Paulo
      POSTGRES_INITDB_ARGS: "--locale=en_US.UTF-8"

    volumes:
      - postgres_data:/var/lib/postgresql/data
     
volumes:
  postgres_data: